apiVersion: v1
kind: Service
metadata:
  labels:
    app: mailhog
  name: mailhog
spec:
  ports:
    - name: smtp 
      port: 1025 # SMTP port
      protocol: TCP
      targetPort: 1025
    - name: http ui 
      port: 8025 # HTTP UI port
      protocol: TCP
      targetPort: 8025
  selector: 
    app: mailhog
  type: ClusterIP