apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: farmercompensationencrypt-prod
  namespace: default
spec:
  acme:
    # now pointing to Let's Encrypt production API
    server: https://acme-v02.api.letsencrypt.org/directory
    email: it2021132@hua.gr
    privateKeySecretRef:
      # storing key material for the ACME account in dedicated secret
      name: farmercompensation-account-key
    solvers:
    - http01:
       ingress:
         class: public